name: fake-news-detection
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly # Change to 'pytorch-cuda' for GPU support if needed
  - pyg
  - pyyaml
  - scikit-learn
  - pandas
  - matplotlib
  - tqdm
  - pip:
    - -e .
